import type { Metadata } from "next";

import { DefaultLayout } from "@/layouts";
import "@/styles/main.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark-mode">
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
